package com.elinex.imagestesttask.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity representing an image record in the local database.
 * 
 * This data class defines the structure of the images table in the Room database.
 * It maps the domain model ImageModel to a persistent database entity for local
 * storage and caching of image data.
 * 
 * Database configuration:
 * - Table name: "images"
 * - Primary key: id (auto-generated Long)
 * - Fields: id, redirectUrl
 * 
 * Key features:
 * - Uses Room annotations for database mapping
 * - Auto-generates primary key for unique identification
 * - Stores redirect URLs for image loading optimization
 * - Provides clean data structure for database operations
 * 
 * This entity is used by the ImageDao for all database operations and
 * serves as the data layer representation of image information.
 * 
 * @see ImageDao
 * @see ImageDatabase
 * @see com.elinex.imagestesttask.domain.model.ImageModel
 * 
 * @author Elinext Test Task Team
 * @since 1.0.0
 */
@Entity(tableName = "images")
data class ImageEntity(
    /**
     * Primary key for the image record.
     * Auto-generated by Room to ensure unique identification.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    
    /**
     * Redirect URL for the image.
     * This URL is used for optimized image loading and caching.
     */
    val redirectUrl: String?
)
